name: GitHub Pages

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  gh-pages-build:
    name: Build GitHub Pages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: "3.13"
        cache: "pip"

    - run: pip install -r requirements.txt

    - name: build docs
      run: |
        mkdocs build

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: site/

  deploy:
    name: Deploy GitHub Pages
    needs: gh-pages-build
    if: ${{ github.ref_name == github.event.repository.default_branch }}

    concurrency:
      group: "github-pages"
      cancel-in-progress: false

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
